---
storage:
  disks:
    - device: /dev/sda
      partitions:
        - label: DOCKER
          number: 10
          start: 19GiB
          type_guid: E6D6D379-F507-44C2-A23C-238F2A3DF928 # LVM

  files:
    - filesystem: root
      path: /etc/hostname
      mode: 420
      contents:
        inline: kubby-1

    - path: /etc/lvm/profile/docker-thinpool.profile
      filesystem: root
      mode: 0644
      contents:
        inline: |
          activation {
              thin_pool_autoextend_threshold=80
              thin_pool_autoextend_percent=20
          }

    - path: /opt/thinpool-init
      filesystem: root
      mode: 0755
      contents:
        inline: |
          #!/bin/bash -ex
          /usr/sbin/wipefs -af /dev/sda10
          /usr/sbin/pvcreate -y /dev/sda10
          /usr/sbin/vgcreate -y docker /dev/sda10
          /usr/sbin/lvcreate -y --wipesignatures y -n thinpool docker -l 95%VG
          /usr/sbin/lvcreate -y --wipesignatures y -n thinpoolmeta docker -l 1%VG
          /usr/sbin/lvconvert -y --zero n -c 512K --thinpool docker/thinpool --poolmetadata docker/thinpoolmeta
          /usr/sbin/lvchange --metadataprofile docker-thinpool docker/thinpool
          /usr/sbin/lvs -o+seg_monitor
          /usr/bin/rm -rfv /var/lib/docker

systemd:
  units:
    - name: sshd.service
      enable: true

    - name: sshd.socket
      mask: true

    - name: lvm2-lvmetad.service
      enable: true

    - name: lvm2-lvmetad.socket
      enable: true

    - name: thinpool-init.service
      enable: true
      contents: |
        [Unit]
        Description=Configure device for docker direct-lvm storage driver
        ConditionFirstBoot=yes
        Before=docker.service
        After=lvm2-lvmetad.service

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=-+/opt/thinpool-init

        [Install]
        RequiredBy=docker.service

docker:
  flags:
    - --storage-driver=devicemapper
    - --storage-opt dm.fs=xfs
    - --storage-opt=dm.thinpooldev=/dev/mapper/docker-thinpool
    - --storage-opt=dm.use_deferred_removal=true
    - --storage-opt=dm.use_deferred_deletion=true

networkd:
  units:
    - name: 10-dhcp.network
      contents: |
        [Match]
        Name=enp1s0

        [Network]
        DHCP=yes
        LinkLocalAddressing=no
        IPv6AcceptRA=no

    - name: 20-static.network
      contents: |
        [Match]
        Name=!enp1s0

        [Network]
        DHCP=no
        LinkLocalAddressing=no
        IPv6AcceptRA=no

passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC595cHiWTMqCal7Pu9vOqFi8aEFixQkVgKvbxo5fpBARUocwEZUntKPYFbdzeDTPPXAS8txE6gpUzgbcfVaJD7JfhVxqO8ayrMe5mdt86YFKQ48JqID6C2mOwm/+j5EyOOfvIwmIUuggtDKp6PSLA0gzHQnEJjBpze4iyVDSXepLZOCai8qX49rL8++rr5t82V0AjGpEVG58n8Es+IBG61xFjYosXz0Oqo6laBEvTak+Nl2fS3Z+sGoyxa0L4DudFWYnH2SA3nzkZqmIdfxv/4rZFgSZZX28nQlOT+ZXMHDK6kVbXKifcqIpcKJZOmyStayAhDBmgSk0mrt+2ijLKV4tn80tWnWGjMg3S8ccf9cNOB4E2mO3Vs3Ri3hxB6aauC+p/SLkRcpLe1ak2LHKtqQQOk8t20zZBn7LlXhLdUedhy0KAglY4Hoq6fld+PsssUv0opcxqkiuVNvK4q+3rYweXOfrA1k4XpPZ3yv70PnVaDcJBKRKLgUsnoo2gSxYxlOM18oMeT312wtFaRl8jRhYfl8FPkyGd8nw4lUW9F5Gecxi3IJLQjgruO0+ZW4ysM0o1A9dXeDtgWml3kpSxVhmRcavG7xLxPfe7LZBSnI0XvPcaeyFkncU1onnA2LYvw735b+oT1v1HmN4v2aCCygVYK/FwMHYXb2ADi1+oZBQ== cardno:000607127116"
        - "ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBACtQrzkg3YPbhljEhvdrEBPPhP/Yr4b8Zaaq480lHDfN4GTeuQi4XEjwbmqvmAOe+RQ8zDhhVqFiryLG029fF1GcgGYYJrqX7W0tW3kYOS/pvBMYDjLazM7UTCf0XZBOKVPqygmBYApHulF7bzoY+xa8Dl8z8iHac84jozdm1m6SdOnzA== mike@juliana"

