apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: greeter
spec:
  selector:
    matchLabels:
      app: greeter
  replicas: 3
  template:
    metadata:
      labels:
        app: greeter
    spec:
      containers:
      - name: helloworld
        image: docker.io/musl/greeter:v1
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: greeter
spec:
  selector:
    app: greeter
  ports:
    - name: web
      port: 80
      protocol: TCP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: greeter
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
    - http:
        paths:
          - path: /greeter
            backend:
              serviceName: greeter
              servicePort: web
