debug = false
logLevel = "INFO"
keepTrailingSlash = true

[traefikLog]
filePath = "/var/log/traefik.log"
#format = "json"

[accessLog]
filePath = "/var/log/traefik-access.log"
#format = "json"

[accessLog.filters]
statusCodes = ["200", "300-302"]
retryAttempts = true
minDuration = "1000ms"

[api]
dashboard = true
debug = true

[entryPoints]
[entryPoints.http]
address = ":80"

[kubernetes]
endpoint = "https://one.kube.net:6443"
token = "eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJ0cmFlZmlrLWluZ3Jlc3MtY29udHJvbGxlci10b2tlbi14NGc0NSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJ0cmFlZmlrLWluZ3Jlc3MtY29udHJvbGxlciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjM0ZmU0MGQ0LTIyNjgtMTFlOS04NmViLTAwMGRiOTRmYTgzYyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTp0cmFlZmlrLWluZ3Jlc3MtY29udHJvbGxlciJ9.x6Wlll_Lp0kUPqTu-uqLFpQ27-0MUBMf8MXiIIZSR0fiM3O3lEsD0GT3WwQzc72tJAM_5e4esmZLSf6xzHG8yJOrUK-JUFAjTCWLIJRBOibmbvkB1xVmlUYGYSN0q8TsbIS6Hb-so4_Av_Rybgt_kMNtB7RXO-81tbWrsZfPOQ6P75u644u_vPrFuTAAjc-mJ27aftz8sNQ7O9_QalmuMwSMI1myqnPzlyquxW_wbL-D7UZf6YYxjn_Uxzq8EFmaWuSjlTH-sxuWAeKT5sQ-BDJBKBlFbjEzkCvhW8aWOSAWoaK6jowXuTd2G2PTExVeUmucg6OW-H09AM9QThBqZw"
certAuthFilePath = "/usr/local/kube.net/pki/ca.crt"
namespaces = []

[ping]

